In [17]:
# Problem 1
import numpy as np

print("ARRAY CREATION TASKS")
print("=" * 50)

# 1. Initialize an empty array with size 2x2
print("1. Empty array with size 2x2:")
empty_array = np.empty((2, 2))
print(empty_array)
print(f"Shape: {empty_array.shape}")
print(f"Data type: {empty_array.dtype}")
print()

# 2. Initialize an all one array with size 4x2
print("2. All ones array with size 4x2:")
ones_array = np.ones((4, 2))
print(ones_array)
print(f"Shape: {ones_array.shape}")
print(f"Data type: {ones_array.dtype}")
print()

# 3. Return a new array of given shape and type, filled with fill value
print("3. Array filled with specific value:")
# Create a 3x3 array filled with value 7
filled_array = np.full((3, 3), 7)
print("3x3 array filled with 7:")
print(filled_array)

# Create a 2x4 array filled with 3.14 (float)
filled_array_float = np.full((2, 4), 3.14)
print("\n2x4 array filled with 3.14:")
print(filled_array_float)

# Create a 1D array filled with -1
filled_1d = np.full(5, -1)
print("\n1D array of size 5 filled with -1:")
print(filled_1d)
print()

# 4. Return a new array of zeros with same shape and type as a given array
print("4. Array of zeros with same shape and type as given array:")
# Create a sample array
sample_array = np.array([[1, 2, 3], [4, 5, 6]], dtype=float)
print("Sample array:")
print(sample_array)
print(f"Shape: {sample_array.shape}, dtype: {sample_array.dtype}")

# Create zeros array with same shape and type
zeros_like_array = np.zeros_like(sample_array)
print("\nZeros array with same shape and type:")
print(zeros_like_array)
print(f"Shape: {zeros_like_array.shape}, dtype: {zeros_like_array.dtype}")

# Another example with integer array
int_array = np.array([[10, 20], [30, 40]])
zeros_like_int = np.zeros_like(int_array)
print("\nInteger array:")
print(int_array)
print("Zeros array with same shape and type:")
print(zeros_like_int)
print(f"dtype: {zeros_like_int.dtype}")
print()

# 5. Return a new array of ones with same shape and type as a given array
print("5. Array of ones with same shape and type as given array:")
# Using the same sample array
ones_like_array = np.ones_like(sample_array)
print("Ones array with same shape and type as sample array:")
print(ones_like_array)
print(f"Shape: {ones_like_array.shape}, dtype: {ones_like_array.dtype}")

# With integer array
ones_like_int = np.ones_like(int_array)
print("\nOnes array with same shape and type as integer array:")
print(ones_like_int)
print(f"dtype: {ones_like_int.dtype}")
print()

# 6. Convert an existing list to numpy array
print("6. Convert list to numpy array:")
new_list = [1, 2, 3, 4]
print(f"Original list: {new_list}")
print(f"Type of list: {type(new_list)}")

# Convert to numpy array
numpy_array = np.array(new_list)
print(f"\nConverted numpy array: {numpy_array}")
print(f"Type of numpy array: {type(numpy_array)}")
print(f"Shape: {numpy_array.shape}")
print(f"Data type: {numpy_array.dtype}")
print()

print("=" * 50)
print("ADDITIONAL EXAMPLES AND COMPARISONS")
print("=" * 50)

# Additional examples for better understanding
print("Comparison of different array creation methods:")

# Empty vs zeros
print("\nEmpty vs Zeros arrays:")
empty_2x2 = np.empty((2, 2))
zeros_2x2 = np.zeros((2, 2))
print("Empty array (contains uninitialized values):")
print(empty_2x2)
print("Zeros array (initialized with 0):")
print(zeros_2x2)

# Full with different data types
print("\nFull arrays with different data types:")
full_int = np.full((2, 2), 5, dtype=int)
full_float = np.full((2, 2), 5, dtype=float)
full_complex = np.full((2, 2), 5, dtype=complex)
print("Integer full array:")
print(full_int)
print("Float full array:")
print(full_float)
print("Complex full array:")
print(full_complex)

# Converting nested lists to 2D arrays
print("\nConverting nested lists to 2D arrays:")
nested_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
nested_array = np.array(nested_list)
print("Nested list:")
for row in nested_list:
    print(row)
print("Converted 2D numpy array:")
print(nested_array)
print(f"Shape: {nested_array.shape}")

# Using zeros_like and ones_like with different dtypes
print("\nzeros_like and ones_like with explicit dtypes:")
complex_array = np.array([[1+2j, 3+4j]], dtype=complex)
zeros_complex = np.zeros_like(complex_array)
ones_complex = np.ones_like(complex_array)
print("Original complex array:")
print(complex_array)
print("Zeros like complex:")
print(zeros_complex)
print("Ones like complex:")
print(ones_complex)

ARRAY CREATION TASKS
1. Empty array with size 2x2:
[[-0.42412518  0.42412518]
 [ 0.17376846 -0.17376846]]
Shape: (2, 2)
Data type: float64

2. All ones array with size 4x2:
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Shape: (4, 2)
Data type: float64

3. Array filled with specific value:
3x3 array filled with 7:
[[7 7 7]
 [7 7 7]
 [7 7 7]]

2x4 array filled with 3.14:
[[3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14]]

1D array of size 5 filled with -1:
[-1 -1 -1 -1 -1]

4. Array of zeros with same shape and type as given array:
Sample array:
[[1. 2. 3.]
 [4. 5. 6.]]
Shape: (2, 3), dtype: float64

Zeros array with same shape and type:
[[0. 0. 0.]
 [0. 0. 0.]]
Shape: (2, 3), dtype: float64

Integer array:
[[10 20]
 [30 40]]
Zeros array with same shape and type:
[[0 0]
 [0 0]]
dtype: int64

5. Array of ones with same shape and type as given array:
Ones array with same shape and type as sample array:
[[1. 1. 1.]
 [1. 1. 1.]]
Shape: (2, 3), dtype: float64

Ones array with same shape and type as intege

In [16]:
# Problem 2
import numpy as np

print("ARRAY MANIPULATION: NUMERICAL RANGES AND ARRAY INDEXING")
print("=" * 60)

# 1. Create an array with values ranging from 10 to 49
print("1. Array with values from 10 to 49:")
arr1 = np.arange(10, 50)
print(arr1)
print(f"Shape: {arr1.shape}, Length: {len(arr1)}")
print()

# 2. Create a 3x3 matrix with values ranging from 0 to 8
print("2. 3x3 matrix with values from 0 to 8:")
arr2 = np.arange(9).reshape(3, 3)
print(arr2)
print(f"Shape: {arr2.shape}")
print()

# 3. Create a 3x3 identity matrix
print("3. 3x3 identity matrix:")
identity_matrix = np.eye(3)
print(identity_matrix)
print(f"Shape: {identity_matrix.shape}")
print()

# 4. Create a random array of size 30 and find the mean
print("4. Random array of size 30 and its mean:")
random_arr = np.random.random(30)
print("Array:", random_arr)
print(f"Mean: {random_arr.mean():.4f}")
print(f"Using array.mean(): {random_arr.mean():.4f}")
print(f"Using np.mean(): {np.mean(random_arr):.4f}")
print()

# 5. Create a 10x10 array with random values and find min/max
print("5. 10x10 random array with min and max values:")
large_array = np.random.random((10, 10))
print("Array shape:", large_array.shape)
print(f"Minimum value: {large_array.min():.4f}")
print(f"Maximum value: {large_array.max():.4f}")
print(f"Minimum value (np.min): {np.min(large_array):.4f}")
print(f"Maximum value (np.max): {np.max(large_array):.4f}")
print()

# 6. Create a zero array of size 10 and replace 5th element with 1
print("6. Zero array of size 10, replace 5th element with 1:")
zero_arr = np.zeros(10)
print("Original array:", zero_arr)
zero_arr[4] = 1  # 5th element (0-based indexing)
print("After replacement:", zero_arr)
print()

# 7. Reverse an array arr = [1,2,0,0,4,0]
print("7. Reverse the array [1,2,0,0,4,0]:")
arr = np.array([1, 2, 0, 0, 4, 0])
print("Original array:", arr)
reversed_arr = arr[::-1]
print("Reversed array:", reversed_arr)

# Alternative methods
print("Alternative method 1 (np.flip):", np.flip(arr))
print("Alternative method 2 (reverse method):", arr[::-1])
print()

# 8. Create a 2D array with 1 on border and 0 inside
print("8. 2D array with 1 on border and 0 inside:")
# Let's create a 5x5 array for demonstration
size = 5
border_array = np.ones((size, size))
border_array[1:-1, 1:-1] = 0  # Set inner elements to 0
print(border_array)
print(f"Shape: {border_array.shape}")

# For a different size
print("\n4x4 example:")
size2 = 4
border_array2 = np.ones((size2, size2))
border_array2[1:-1, 1:-1] = 0
print(border_array2)
print()

# 9. Create a 8x8 matrix with checkerboard pattern
print("9. 8x8 checkerboard pattern:")
# Method 1: Using slicing
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1  # Odd rows, even columns
checkerboard[::2, 1::2] = 1  # Even rows, odd columns
print("Method 1 (slicing):")
print(checkerboard)

# Method 2: Using tile
print("\nMethod 2 (using np.tile):")
base_pattern = np.array([[0, 1], [1, 0]])
checkerboard2 = np.tile(base_pattern, (4, 4))
print(checkerboard2)

# Method 3: Using addition and modulo
print("\nMethod 3 (using indices):")
rows, cols = np.indices((8, 8))
checkerboard3 = (rows + cols) % 2
print(checkerboard3)

print("\n" + "=" * 60)
print("ADDITIONAL EXAMPLES AND VERIFICATIONS")
print("=" * 60)

# Additional verification for the checkerboard pattern
print("Checkerboard pattern verification:")
print("Sum of all elements (should be 32 for 8x8):", np.sum(checkerboard))
print("Pattern repeats correctly:", np.array_equal(checkerboard, checkerboard2))

# Demonstrate array indexing techniques
print("\nArray Indexing Examples:")
demo_array = np.arange(1, 21).reshape(4, 5)
print("Demo array:")
print(demo_array)
print("Element at [2, 3]:", demo_array[2, 3])
print("First row:", demo_array[0])
print("Last column:", demo_array[:, -1])
print("Sub-array (rows 1-2, columns 2-4):")
print(demo_array[1:3, 2:5])

ARRAY MANIPULATION: NUMERICAL RANGES AND ARRAY INDEXING
1. Array with values from 10 to 49:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
Shape: (40,), Length: 40

2. 3x3 matrix with values from 0 to 8:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Shape: (3, 3)

3. 3x3 identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Shape: (3, 3)

4. Random array of size 30 and its mean:
Array: [0.73594882 0.7059138  0.21263915 0.13788404 0.5432991  0.84392562
 0.40011053 0.92405868 0.59817698 0.57667236 0.08016328 0.57195213
 0.86058139 0.58243318 0.70843752 0.81908499 0.47608384 0.80413989
 0.30420054 0.78074927 0.06296887 0.75135716 0.47451462 0.35666084
 0.57980473 0.96480533 0.22901426 0.10776743 0.50494056 0.47618575]
Mean: 0.5391
Using array.mean(): 0.5391
Using np.mean(): 0.5391

5. 10x10 random array with min and max values:
Array shape: (10, 10)
Minimum value: 0.0123
Maximum value: 0.9954
Minimum value (np.min): 0.0123
Maximum 

In [14]:
# Problem-3
import numpy as np

# Define the arrays
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

print("Original arrays:")
print("x =", x)
print("y =", y)
print("v =", v)
print("w =", w)
print()

# 1. Add the two arrays
print("1. Array Addition:")
print("x + y =")
print(x + y)
print()

# 2. Subtract the two arrays
print("2. Array Subtraction:")
print("x - y =")
print(x - y)
print()

# 3. Multiply the array with any integers of your choice
print("3. Array Multiplication with scalar:")
multiplier = 3
print(f"x * {multiplier} =")
print(x * multiplier)
print(f"v * {multiplier} =")
print(v * multiplier)
print()

# 4. Find the square of each element of the array
print("4. Square of each element:")
print("x² =")
print(x ** 2)
print("v² =")
print(v ** 2)
print()

# 5. Find the dot product
print("5. Dot products:")
print("v · w =", np.dot(v, w))
print("x · v =", np.dot(x, v))
print("x · y =")
print(np.dot(x, y))
print()

# 6. Concatenation operations
print("6. Concatenation:")
print("x and y along row:")
xy_row = np.concatenate((x, y), axis=0)
print(xy_row)

print("v and w along column:")
vw_col = np.vstack((v, w)).T  # Using vstack and transpose to get column arrangement
print(vw_col)

# Alternative method using concatenate
vw_col_alt = np.concatenate((v.reshape(-1,1), w.reshape(-1,1)), axis=1)
print("Alternative method:")
print(vw_col_alt)
print()

# 7. Concatenate x and v
print("7. Concatenating x and v:")
try:
    xv_concat = np.concatenate((x, v))
    print("Success:", xv_concat)
except ValueError as e:
    print("Error occurred:", e)
    print("Explanation: Cannot concatenate x (shape {}) and v (shape {})".format(x.shape, v.shape))
    print("Reason: All input arrays must have the same number of dimensions for concatenation.")
    print("x is 2D array (2x2) while v is 1D array (2,)")

Original arrays:
x = [[1 2]
 [3 5]]
y = [[5 6]
 [7 8]]
v = [ 9 10]
w = [11 12]

1. Array Addition:
x + y =
[[ 6  8]
 [10 13]]

2. Array Subtraction:
x - y =
[[-4 -4]
 [-4 -3]]

3. Array Multiplication with scalar:
x * 3 =
[[ 3  6]
 [ 9 15]]
v * 3 =
[27 30]

4. Square of each element:
x² =
[[ 1  4]
 [ 9 25]]
v² =
[ 81 100]

5. Dot products:
v · w = 219
x · v = [29 77]
x · y =
[[19 22]
 [50 58]]

6. Concatenation:
x and y along row:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
v and w along column:
[[ 9 11]
 [10 12]]
Alternative method:
[[ 9 11]
 [10 12]]

7. Concatenating x and v:
Error occurred: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Explanation: Cannot concatenate x (shape (2, 2)) and v (shape (2,))
Reason: All input arrays must have the same number of dimensions for concatenation.
x is 2D array (2x2) while v is 1D array (2,)


In [15]:
# Problem 4
import numpy as np

print("MATRIX OPERATIONS")
print("=" * 50)

# Define matrices A and B
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)

# 1. Prove A.A⁻¹ = I
print("\n1. Proving A.A⁻¹ = I:")
try:
    A_inv = np.linalg.inv(A)
    print("A⁻¹ =")
    print(A_inv)

    identity_check = np.dot(A, A_inv)
    print("\nA.A⁻¹ =")
    print(identity_check)
    print("\nIs A.A⁻¹ approximately equal to I?", np.allclose(identity_check, np.eye(2)))
except np.linalg.LinAlgError:
    print("Matrix A is singular, cannot compute inverse")

# 2. Prove AB ≠ BA
print("\n2. Proving AB ≠ BA:")
AB = np.dot(A, B)
BA = np.dot(B, A)

print("AB =")
print(AB)
print("\nBA =")
print(BA)
print("\nIs AB equal to BA?", np.array_equal(AB, BA))

# 3. Prove (AB)ᵀ = BᵀAᵀ
print("\n3. Proving (AB)ᵀ = BᵀAᵀ:")
AB_transpose = AB.T
B_transpose_A_transpose = np.dot(B.T, A.T)

print("(AB)ᵀ =")
print(AB_transpose)
print("\nBᵀAᵀ =")
print(B_transpose_A_transpose)
print("\nIs (AB)ᵀ equal to BᵀAᵀ?", np.array_equal(AB_transpose, B_transpose_A_transpose))

print("\n" + "=" * 50)
print("SOLVING SYSTEM OF LINEAR EQUATIONS")
print("=" * 50)

# System of equations:
# 2x - 3y + z = -1
# x - y + 2z = -3
# 3x + y - z = 9

# Represent in matrix form: AX = B
A_matrix = np.array([[2, -3, 1],
                     [1, -1, 2],
                     [3, 1, -1]])

B_vector = np.array([-1, -3, 9])

print("Coefficient matrix A:")
print(A_matrix)
print("\nConstant vector B:")
print(B_vector)

# Method 1: Using np.linalg.inv
print("\nMethod 1: Using Inverse Method (A⁻¹B)")
try:
    A_inv = np.linalg.inv(A_matrix)
    print("A⁻¹ =")
    print(A_inv)

    solution_inv = np.dot(A_inv, B_vector)
    print(f"\nSolution using inverse method:")
    print(f"x = {solution_inv[0]:.2f}")
    print(f"y = {solution_inv[1]:.2f}")
    print(f"z = {solution_inv[2]:.2f}")

    # Verify the solution
    verification = np.dot(A_matrix, solution_inv)
    print(f"\nVerification (A * X): {verification}")
    print(f"Original B: {B_vector}")
    print(f"Solution is correct: {np.allclose(verification, B_vector)}")

except np.linalg.LinAlgError:
    print("Matrix is singular, cannot use inverse method")

# Method 2: Using np.linalg.solve (more numerically stable)
print("\n" + "-" * 30)
print("Method 2: Using np.linalg.solve")
try:
    solution_solve = np.linalg.solve(A_matrix, B_vector)
    print(f"Solution using np.linalg.solve:")
    print(f"x = {solution_solve[0]:.2f}")
    print(f"y = {solution_solve[1]:.2f}")
    print(f"z = {solution_solve[2]:.2f}")

    # Verify the solution
    verification_solve = np.dot(A_matrix, solution_solve)
    print(f"\nVerification (A * X): {verification_solve}")
    print(f"Solution is correct: {np.allclose(verification_solve, B_vector)}")

except np.linalg.LinAlgError:
    print("Matrix is singular, cannot solve")

print("\n" + "=" * 50)
print("EXPLORING NUMPY LINALG FUNCTIONS")
print("=" * 50)

# Exploring more linalg functions
print("Additional linalg function examples:")

# Determinant
det_A = np.linalg.det(A_matrix)
print(f"Determinant of A: {det_A:.2f}")

# Rank
rank_A = np.linalg.matrix_rank(A_matrix)
print(f"Rank of A: {rank_A}")

# Eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A_matrix)
print(f"Eigenvalues of A: {eigenvalues}")
print("Eigenvectors of A:")
print(eigenvectors)

# Matrix norm
norm_A = np.linalg.norm(A_matrix)
print(f"Frobenius norm of A: {norm_A:.2f}")

# Condition number
cond_A = np.linalg.cond(A_matrix)
print(f"Condition number of A: {cond_A:.2f}")

MATRIX OPERATIONS
Matrix A:
[[3 4]
 [7 8]]

Matrix B:
[[5 3]
 [2 1]]

1. Proving A.A⁻¹ = I:
A⁻¹ =
[[-2.    1.  ]
 [ 1.75 -0.75]]

A.A⁻¹ =
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

Is A.A⁻¹ approximately equal to I? True

2. Proving AB ≠ BA:
AB =
[[23 13]
 [51 29]]

BA =
[[36 44]
 [13 16]]

Is AB equal to BA? False

3. Proving (AB)ᵀ = BᵀAᵀ:
(AB)ᵀ =
[[23 51]
 [13 29]]

BᵀAᵀ =
[[23 51]
 [13 29]]

Is (AB)ᵀ equal to BᵀAᵀ? True

SOLVING SYSTEM OF LINEAR EQUATIONS
Coefficient matrix A:
[[ 2 -3  1]
 [ 1 -1  2]
 [ 3  1 -1]]

Constant vector B:
[-1 -3  9]

Method 1: Using Inverse Method (A⁻¹B)
A⁻¹ =
[[ 0.05263158  0.10526316  0.26315789]
 [-0.36842105  0.26315789  0.15789474]
 [-0.21052632  0.57894737 -0.05263158]]

Solution using inverse method:
x = 2.00
y = 1.00
z = -2.00

Verification (A * X): [-1. -3.  9.]
Original B: [-1 -3  9]
Solution is correct: True

------------------------------
Method 2: Using np.linalg.solve
Solution using np.linalg.solve:
x = 2.00
y = 1.00